sudo: required
services:
  - docker

before_install:
  - docker build -t julianz7/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true julianz7/docker-react-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-360149086885"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
      secure: "$AWS_SECRET_KEY"